/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignment2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Roronoa
 */
public class MainForm extends java.awt.Frame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        dirtyRead = new javax.swing.JButton();
        unrepeatableRead = new javax.swing.JButton();
        phantomRead = new javax.swing.JButton();
        deadlock = new javax.swing.JButton();
        threads = new javax.swing.JSpinner();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        dirtyRead.setText("Dirty Read");
        jPanel2.add(dirtyRead);
        
        dirtyRead.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				Database db = new Database();
				
			}
		});

        unrepeatableRead.setText("Unrepeatable read");
        jPanel2.add(unrepeatableRead);

        phantomRead.setText("Phantom read");
        jPanel2.add(phantomRead);

        deadlock.setText("Deadlock");
        jPanel2.add(deadlock);

        threads.setToolTipText("Select the number of threads");
        jPanel2.add(threads);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deadlock;
    private javax.swing.JButton dirtyRead;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton phantomRead;
    private javax.swing.JSpinner threads;
    private javax.swing.JButton unrepeatableRead;
    // End of variables declaration//GEN-END:variables
}
